# -*- coding: utf-8 -*-
"""Mean, Count, Fit .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XjQ8wkPXW0qqFVFwomerESIKVxpeOnY

**Diff E_0 AND T_0**
"""

import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from mpl_toolkits.mplot3d import Axes3D

# Parameters
N_steps = 200
L = 1.0
r = 0.02
m = 0.02
k_on = 0.8
k_off = 0.6
k_kill = 0.2
g_E = 0.0
g_T = 0.05
early_stop = (10, 0.01)
log_all = False

# 3D Surface: F vs E_0 and T_0
E_0_values = np.linspace(0, 300, 10, dtype=int)
T_0_values = np.linspace(50, 300, 10, dtype=int)
F_matrix = np.zeros((len(E_0_values), len(T_0_values)))

for i, E_0 in enumerate(tqdm(E_0_values, desc="E_0 Sweep")):
    for j, T_0 in enumerate(T_0_values):
        sim_with_E = WellSimulation(E_0=E_0, T_0=T_0, r=r, m=m, N=N_steps, L=L,
                                    k_on=k_on, k_off=k_off, k_kill=k_kill,
                                    g_E=g_E, g_T=g_T, early_stop=early_stop,
                                    log_all=log_all, seed=42)
        sim_with_E.run()
        T_with_E = sim_with_E.history['T'][-1]

        sim_no_E = WellSimulation(E_0=0, T_0=T_0, r=r, m=m, N=N_steps, L=L,
                                  k_on=k_on, k_off=k_off, k_kill=k_kill,
                                  g_E=g_E, g_T=g_T, early_stop=early_stop,
                                  log_all=log_all, seed=42)
        sim_no_E.run()
        T_no_E = sim_no_E.history['T'][-1]

        F = T_with_E / T_no_E if T_no_E > 0 else np.nan
        F_matrix[i, j] = F

E_grid, T_grid = np.meshgrid(T_0_values, E_0_values)
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection='3d')
surf = ax.plot_surface(E_grid, T_grid, F_matrix, cmap='viridis')
ax.set_xlabel('T_0 (Target Cells)')
ax.set_ylabel('E_0 (Effector Cells)')
ax.set_zlabel('F = T(t_f; E_0, T_0) / T(t_f; 0, T_0)')
ax.set_title('F Surface vs E_0 and T_0 (E:T Sweep)')
fig.colorbar(surf, shrink=0.5, aspect=10)
plt.tight_layout()
plt.show()

# Stochastic T(t) trajectories under different E:T ratios
ratios = [0.1, 0.5, 1, 2, 5]
T_0_fixed = 500
N_replicates = 5

plt.figure(figsize=(10, 6))
for ratio in ratios:
    E_0 = int(ratio * T_0_fixed)
    for seed in range(N_replicates):
        sim = WellSimulation(E_0=E_0, T_0=T_0_fixed, r=r, m=m, N=N_steps, L=L,
                             k_on=k_on, k_off=k_off, k_kill=k_kill,
                             g_E=g_E, g_T=g_T, early_stop=early_stop,
                             log_all=log_all, seed=seed)
        sim.run()
        T_traj = sim.history['T']
        plt.plot(np.arange(len(T_traj)), T_traj, alpha=0.5, label=f'E:T={ratio}:1' if seed==0 else "")

plt.xlabel('Time Step (t)')
plt.ylabel('Target Cell Count T(t)')
plt.title(f'Stochastic T(t) Trajectories at Different E:T Ratios, T_0={T_0_fixed}')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from mpl_toolkits.mplot3d import Axes3D

# Parameters
N_steps = 200
L = 1.0
r = 0.02
m = 0.02
k_on = 0.8
k_off = 0.6
k_kill = 0.2
g_E = 0.0
g_T = 0.05
early_stop = (10, 0.01)
log_all = False

# Precompute T_no_E analytically since there is no killing when E_0=0
def compute_T_no_E(T_0, g_T, N_steps):
    return int(T_0 * ((1 + g_T) ** N_steps))

# 3D Surface: F vs E_0 and T_0
E_0_values = np.linspace(0, 300, 10, dtype=int)
T_0_values = np.linspace(50, 300, 10, dtype=int)
F_matrix = np.zeros((len(E_0_values), len(T_0_values)))

for i, E_0 in enumerate(tqdm(E_0_values, desc="E_0 Sweep")):
    for j, T_0 in enumerate(T_0_values):
        sim_with_E = WellSimulation(E_0=E_0, T_0=T_0, r=r, m=m, N=N_steps, L=L,
                                    k_on=k_on, k_off=k_off, k_kill=k_kill,
                                    g_E=g_E, g_T=g_T, early_stop=early_stop,
                                    log_all=log_all, seed=42)
        sim_with_E.run()
        T_with_E = sim_with_E.history['T'][-1]

        # Instead of simulating, compute T_no_E analytically
        T_no_E = compute_T_no_E(T_0, g_T, N_steps)

        F = T_with_E / T_no_E if T_no_E > 0 else np.nan
        F_matrix[i, j] = F

E_grid, T_grid = np.meshgrid(T_0_values, E_0_values)
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection='3d')
surf = ax.plot_surface(E_grid, T_grid, F_matrix, cmap='viridis')
ax.set_xlabel('T_0 (Target Cells)')
ax.set_ylabel('E_0 (Effector Cells)')
ax.set_zlabel('F = T(t_f; E_0, T_0) / T(t_f; 0, T_0)')
ax.set_title('F Surface vs E_0 and T_0 (E:T Sweep)')
fig.colorbar(surf, shrink=0.5, aspect=10)
plt.tight_layout()
plt.show()

# Stochastic T(t) trajectories under different E:T ratios
ratios = [0.1, 0.5, 1, 2, 5]
T_0_fixed = 500
N_replicates = 5

plt.figure(figsize=(10, 6))
for ratio in ratios:
    E_0 = int(ratio * T_0_fixed)
    for seed in range(N_replicates):
        sim = WellSimulation(E_0=E_0, T_0=T_0_fixed, r=r, m=m, N=N_steps, L=L,
                             k_on=k_on, k_off=k_off, k_kill=k_kill,
                             g_E=g_E, g_T=g_T, early_stop=early_stop,
                             log_all=log_all, seed=seed)
        sim.run()
        T_traj = sim.history['T']
        plt.plot(np.arange(len(T_traj)), T_traj, alpha=0.5, label=f'E:T={ratio}:1' if seed==0 else "")

plt.xlabel('Time Step (t)')
plt.ylabel('Target Cell Count T(t)')
plt.title(f'Stochastic T(t) Trajectories at Different E:T Ratios, T_0={T_0_fixed}')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""ABM TO GENERATE DATA"""

# --- Cell 1: Imports ---
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm


# --- Cell 2: SquareWell class ---
class SquareWell:
    def __init__(self, size: float, mode: str = "reflect") -> None:
        self.L = size
        self.mode = mode

    def random_position(self):
        return tuple(np.random.uniform(0, self.L, size=2))

    def apply_boundary(self, x, y):
        if self.mode == "reflect":
            return np.clip(x, 0, self.L), np.clip(y, 0, self.L)
        else:  # wrap
            return x % self.L, y % self.L


# --- Cell 3: Cell dataclasses ---
from dataclasses import dataclass

@dataclass
class ECell:
    x: float
    y: float

@dataclass
class TCell:
    x: float
    y: float

@dataclass
class CCell:
    x: float
    y: float


# --- Cell 4: ABM Simulation Class ---
class WellSimulation:
    def __init__(self, E_0, T_0, r, m, N, L, k_on, k_off, k_kill, g_E, g_T, early_stop, log_all=False, seed=None):
        if seed is not None:
            np.random.seed(seed)

        self.E_0 = E_0
        self.T_0 = T_0
        self.r = r
        self.m = m
        self.N = N
        self.L = L
        self.k_on = k_on
        self.k_off = k_off
        self.k_kill = k_kill
        self.g_E = g_E
        self.g_T = g_T
        self.early_stop = early_stop
        self.log_all = log_all

        self.history = {"E": [], "T": [], "C": []}
        self.well = SquareWell(L)

        self.e_cells = [ECell(*self.well.random_position()) for _ in range(E_0)]
        self.t_cells = [TCell(*self.well.random_position()) for _ in range(T_0)]
        self.existing_c_cells = []
        self.new_c_cells = []
        self.simulated = False
        self._log()

    def _combine_behavior(self):
        from scipy.spatial import cKDTree
        e_coords = np.array([[e.x, e.y] for e in self.e_cells])
        t_coords = np.array([[t.x, t.y] for t in self.t_cells])
        if len(e_coords) == 0 or len(t_coords) == 0:
            return
        tree = cKDTree(t_coords)
        neighbor_indices = tree.query_ball_point(e_coords, r=2 * self.r)
        taken_t = set()
        new_c = []
        remaining_e = []

        for i, t_neighbors in enumerate(neighbor_indices):
            np.random.shuffle(t_neighbors)
            for j in t_neighbors:
                if j in taken_t:
                    continue
                if np.random.rand() < self.k_on:
                    ex, ey = e_coords[i]
                    tx, ty = t_coords[j]
                    new_c.append(CCell((ex + tx) / 2, (ey + ty) / 2))
                    taken_t.add(j)
                    break
            else:
                remaining_e.append(ECell(*e_coords[i]))

        self.t_cells = [t for j, t in enumerate(self.t_cells) if j not in taken_t]
        self.new_c_cells = new_c
        self.e_cells = remaining_e

    def _c_cell_behavior(self):
        remaining_c = []
        for c in self.existing_c_cells:
            rnd = np.random.rand()
            if rnd < self.k_off:
                self.e_cells.append(ECell(c.x, c.y))
                self.t_cells.append(TCell(c.x, c.y))
            elif rnd < self.k_off + self.k_kill:
                self.e_cells.append(ECell(c.x, c.y))
            else:
                remaining_c.append(c)
        self.existing_c_cells = remaining_c

    def _cell_move(self):
        moved = []
        for e in self.e_cells:
            dx, dy = np.random.normal(0, self.m, size=2)
            x, y = self.well.apply_boundary(e.x + dx, e.y + dy)
            moved.append(ECell(x, y))
        self.e_cells = moved

    def _cell_grow(self):
        new_e = []
        for e in self.e_cells:
            if np.random.rand() < self.g_E:
                dx, dy = np.random.uniform(-self.r, self.r, 2)
                x, y = self.well.apply_boundary(e.x + dx, e.y + dy)
                new_e.append(ECell(x, y))
        self.e_cells.extend(new_e)

        new_t = []
        for t in self.t_cells:
            if np.random.rand() < self.g_T:
                dx, dy = np.random.uniform(-self.r, self.r, 2)
                x, y = self.well.apply_boundary(t.x + dx, t.y + dy)
                new_t.append(TCell(x, y))
        self.t_cells.extend(new_t)

    def _log(self):
        self.history["E"].append(len(self.e_cells))
        self.history["T"].append(len(self.t_cells))
        self.history["C"].append(len(self.existing_c_cells) + len(self.new_c_cells))
        self.existing_c_cells += self.new_c_cells
        self.new_c_cells = []

    def _step(self):
        self._cell_move()
        self._combine_behavior()
        self._c_cell_behavior()
        self._cell_grow()
        self._log()

    def run(self):
        unchanged = 0
        prev_T = self.history["T"][-1]
        for _ in range(self.N):
            self._step()
            curr_T = self.history["T"][-1]
            if prev_T * (1 - self.early_stop[1]) <= curr_T <= prev_T * (1 + self.early_stop[1]):
                unchanged += 1
            else:
                unchanged = 0
            prev_T = curr_T
            if curr_T == 0 and self.history["C"][-1] == 0:
                break
            if self.history["E"][-1] == 0 and self.history["C"][-1] == 0:
                break
            if unchanged >= self.early_stop[0]:
                break
        self.simulated = True


# --- Cell 5: Run ABM to Generate T(t) Data ---
# Parameters
N_steps = 200
E_0 = 100
T_0 = 100
n_replicates = 20

# Run ABM
T_trajectories = []
for seed in tqdm(range(n_replicates), desc="Simulating ABM replicates"):
    sim = WellSimulation(E_0=E_0, T_0=T_0, r=0.02, m=0.02, N=N_steps, L=1.0,
                         k_on=0.8, k_off=0.6, k_kill=0.2,
                         g_E=0.0, g_T=0.05,
                         early_stop=(10, 0.01), log_all=False, seed=seed)
    sim.run()
    T_trajectories.append(sim.history["T"])


# --- Cell 6: Plot Mean and Stochastic T(t) ---
#T_array = np.array([np.pad(t, (0, N_steps - len(t)), constant_values=np.nan) for t in T_trajectories])
T_array = np.array([
    t + [np.nan] * (N_steps - len(t)) if len(t) < N_steps else t[:N_steps]
    for t in T_trajectories
])

T_mean = np.nanmean(T_array, axis=0)
T_std = np.nanstd(T_array, axis=0)

plt.figure(figsize=(10, 6))
for traj in T_array:
    plt.plot(traj, color='lightcoral', alpha=0.4)
plt.plot(T_mean, color='darkred', label='Mean T(t)')
plt.fill_between(np.arange(N_steps), T_mean - T_std, T_mean + T_std, color='pink', alpha=0.3)
plt.xlabel("Time step (t)")
plt.ylabel("Target cell count T(t)")
plt.title(f"ABM-generated T(t) trajectories ({n_replicates} replicates)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd

# Convert to DataFrame: each column = one replicate
df = pd.DataFrame(T_array.T, columns=[f"replicate_{i}" for i in range(n_replicates)])
df["timestep"] = np.arange(N_steps)

# Save to CSV
df.to_csv("ABM_T_trajectories.csv", index=False)

print("✅ CSV file saved: ABM_T_trajectories.csv")



from google.colab import files
files.download("ABM_T_trajectories.csv")

"""ABM EXTENTED GENERATED CODE"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from dataclasses import dataclass

# --- SquareWell Class ---
class SquareWell:
    def __init__(self, size: float, mode: str = "reflect") -> None:
        self.L = size
        self.mode = mode

    def random_position(self):
        return tuple(np.random.uniform(0, self.L, size=2))

    def apply_boundary(self, x, y):
        if self.mode == "reflect":
            return np.clip(x, 0, self.L), np.clip(y, 0, self.L)
        else:
            return x % self.L, y % self.L

# --- Cell Data Classes ---
@dataclass
class ECell:
    x: float
    y: float

@dataclass
class TCell:
    x: float
    y: float

@dataclass
class CCell:
    x: float
    y: float

# --- ABM Simulation Class ---
class WellSimulation:
    def __init__(self, E_0, T_0, r, m, N, L, k_on, k_off, k_kill, g_E, g_T, early_stop, log_all=False, seed=None):
        if seed is not None:
            np.random.seed(seed)

        self.E_0 = E_0
        self.T_0 = T_0
        self.r = r
        self.m = m
        self.N = N
        self.L = L
        self.k_on = k_on
        self.k_off = k_off
        self.k_kill = k_kill
        self.g_E = g_E
        self.g_T = g_T
        self.early_stop = early_stop
        self.log_all = log_all

        self.history = {"E": [], "T": [], "C": []}
        self.well = SquareWell(L)

        self.e_cells = [ECell(*self.well.random_position()) for _ in range(E_0)]
        self.t_cells = [TCell(*self.well.random_position()) for _ in range(T_0)]
        self.existing_c_cells = []
        self.new_c_cells = []
        self.simulated = False
        self._log()

    def _combine_behavior(self):
        from scipy.spatial import cKDTree
        e_coords = np.array([[e.x, e.y] for e in self.e_cells])
        t_coords = np.array([[t.x, t.y] for t in self.t_cells])
        if len(e_coords) == 0 or len(t_coords) == 0:
            return
        tree = cKDTree(t_coords)
        neighbor_indices = tree.query_ball_point(e_coords, r=2 * self.r)
        taken_t = set()
        new_c = []
        remaining_e = []

        for i, t_neighbors in enumerate(neighbor_indices):
            np.random.shuffle(t_neighbors)
            for j in t_neighbors:
                if j in taken_t:
                    continue
                if np.random.rand() < self.k_on:
                    ex, ey = e_coords[i]
                    tx, ty = t_coords[j]
                    new_c.append(CCell((ex + tx) / 2, (ey + ty) / 2))
                    taken_t.add(j)
                    break
            else:
                remaining_e.append(ECell(*e_coords[i]))

        self.t_cells = [t for j, t in enumerate(self.t_cells) if j not in taken_t]
        self.new_c_cells = new_c
        self.e_cells = remaining_e

    def _c_cell_behavior(self):
        remaining_c = []
        for c in self.existing_c_cells:
            rnd = np.random.rand()
            if rnd < self.k_off:
                self.e_cells.append(ECell(c.x, c.y))
                self.t_cells.append(TCell(c.x, c.y))
            elif rnd < self.k_off + self.k_kill:
                self.e_cells.append(ECell(c.x, c.y))
            else:
                remaining_c.append(c)
        self.existing_c_cells = remaining_c

    def _cell_move(self):
        moved = []
        for e in self.e_cells:
            dx, dy = np.random.normal(0, self.m, size=2)
            x, y = self.well.apply_boundary(e.x + dx, e.y + dy)
            moved.append(ECell(x, y))
        self.e_cells = moved

    def _cell_grow(self):
        new_e = []
        for e in self.e_cells:
            if np.random.rand() < self.g_E:
                dx, dy = np.random.uniform(-self.r, self.r, 2)
                x, y = self.well.apply_boundary(e.x + dx, e.y + dy)
                new_e.append(ECell(x, y))
        self.e_cells.extend(new_e)

        new_t = []
        for t in self.t_cells:
            if np.random.rand() < self.g_T:
                dx, dy = np.random.uniform(-self.r, self.r, 2)
                x, y = self.well.apply_boundary(t.x + dx, t.y + dy)
                new_t.append(TCell(x, y))
        self.t_cells.extend(new_t)

    def _log(self):
        self.history["E"].append(len(self.e_cells))
        self.history["T"].append(len(self.t_cells))
        self.history["C"].append(len(self.existing_c_cells) + len(self.new_c_cells))
        self.existing_c_cells += self.new_c_cells
        self.new_c_cells = []

    def _step(self):
        self._cell_move()
        self._combine_behavior()
        self._c_cell_behavior()
        self._cell_grow()
        self._log()

    def run(self):
        unchanged = 0
        prev_T = self.history["T"][-1]
        for _ in range(self.N):
            self._step()
            curr_T = self.history["T"][-1]
            if prev_T * (1 - self.early_stop[1]) <= curr_T <= prev_T * (1 + self.early_stop[1]):
                unchanged += 1
            else:
                unchanged = 0
            prev_T = curr_T
            if curr_T == 0 and self.history["C"][-1] == 0:
                break
            if self.history["E"][-1] == 0 and self.history["C"][-1] == 0:
                break
            if unchanged >= self.early_stop[0]:
                break
        self.simulated = True

# --- Run ABM and Collect Full Data ---
N_steps = 200
E_0 = 100
T_0 = 100
n_replicates = 100

E_all, T_all, C_all = [], [], []
records = []

for seed in tqdm(range(n_replicates), desc="Simulating ABM replicates"):
    sim = WellSimulation(E_0=E_0, T_0=T_0, r=0.02, m=0.02, N=N_steps, L=1.0,
                         k_on=0.8, k_off=0.6, k_kill=0.2,
                         g_E=0.0, g_T=0.05,
                         early_stop=(10, 0.01), log_all=False, seed=seed)
    sim.run()
    E_all.append(sim.history["E"])
    T_all.append(sim.history["T"])
    C_all.append(sim.history["C"])
    for t in range(len(sim.history["T"])):
        records.append({"replicate": seed, "timestep": t,
                        "E": sim.history["E"][t],
                        "T": sim.history["T"][t],
                        "C": sim.history["C"][t]})

# --- Long Format ---
long_df = pd.DataFrame.from_records(records)
long_df.to_csv("ABM_E_T_C_long.csv", index=False)

# --- Wide Format: Individual ---
max_len = max(max(len(e) for e in E_all), max(len(t) for t in T_all), max(len(c) for c in C_all))

def pad_to_max(lst):
    return lst + [np.nan] * (max_len - len(lst))

E_df = pd.DataFrame(np.array([pad_to_max(e) for e in E_all]).T, columns=[f"rep_{i}" for i in range(n_replicates)])
T_df = pd.DataFrame(np.array([pad_to_max(t) for t in T_all]).T, columns=[f"rep_{i}" for i in range(n_replicates)])
C_df = pd.DataFrame(np.array([pad_to_max(c) for c in C_all]).T, columns=[f"rep_{i}" for i in range(n_replicates)])

E_df["timestep"] = T_df["timestep"] = C_df["timestep"] = np.arange(max_len)
E_df.to_csv("ABM_E_wide.csv", index=False)
T_df.to_csv("ABM_T_wide.csv", index=False)
C_df.to_csv("ABM_C_wide.csv", index=False)

# --- Aggregated Statistics ---
aggr_df = pd.DataFrame({
    "timestep": np.arange(max_len),
    "E_mean": np.nanmean(E_df.drop("timestep", axis=1), axis=1),
    "T_mean": np.nanmean(T_df.drop("timestep", axis=1), axis=1),
    "C_mean": np.nanmean(C_df.drop("timestep", axis=1), axis=1),
    "E_std": np.nanstd(E_df.drop("timestep", axis=1), axis=1),
    "T_std": np.nanstd(T_df.drop("timestep", axis=1), axis=1),
    "C_std": np.nanstd(C_df.drop("timestep", axis=1), axis=1),
})
aggr_df.to_csv("ABM_ETC_summary.csv", index=False)

print("✅ All CSV files saved.")

from google.colab import files
files.download("ABM_ETC_summary.csv")

from google.colab import files
files.download("ABM_ETC_summary.csv")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from dataclasses import dataclass

# --- SquareWell Class ---
class SquareWell:
    def __init__(self, size: float, mode: str = "reflect") -> None:
        self.L = size
        self.mode = mode

    def random_position(self):
        return tuple(np.random.uniform(0, self.L, size=2))

    def apply_boundary(self, x, y):
        if self.mode == "reflect":
            return np.clip(x, 0, self.L), np.clip(y, 0, self.L)
        else:
            return x % self.L, y % self.L

# --- Cell Data Classes ---
@dataclass
class ECell:
    x: float
    y: float

@dataclass
class TCell:
    x: float
    y: float

@dataclass
class CCell:
    x: float
    y: float

# --- ABM Simulation Class ---
class WellSimulation:
    def __init__(self, E_0, T_0, r, m, N, L, k_on, k_off, k_kill, g_E, g_T, early_stop, log_all=False, seed=None):
        if seed is not None:
            np.random.seed(seed)

        self.E_0 = E_0
        self.T_0 = T_0
        self.r = r
        self.m = m
        self.N = N
        self.L = L
        self.k_on = k_on
        self.k_off = k_off
        self.k_kill = k_kill
        self.g_E = g_E
        self.g_T = g_T
        self.early_stop = early_stop
        self.log_all = log_all

        self.history = {"E": [], "T": [], "C": []}
        self.well = SquareWell(L)

        self.e_cells = [ECell(*self.well.random_position()) for _ in range(E_0)]
        self.t_cells = [TCell(*self.well.random_position()) for _ in range(T_0)]
        self.existing_c_cells = []
        self.new_c_cells = []
        self.simulated = False
        self._log()

    def _combine_behavior(self):
        from scipy.spatial import cKDTree
        e_coords = np.array([[e.x, e.y] for e in self.e_cells])
        t_coords = np.array([[t.x, t.y] for t in self.t_cells])
        if len(e_coords) == 0 or len(t_coords) == 0:
            return
        tree = cKDTree(t_coords)
        neighbor_indices = tree.query_ball_point(e_coords, r=2 * self.r)
        taken_t = set()
        new_c = []
        remaining_e = []

        for i, t_neighbors in enumerate(neighbor_indices):
            np.random.shuffle(t_neighbors)
            for j in t_neighbors:
                if j in taken_t:
                    continue
                if np.random.rand() < self.k_on:
                    ex, ey = e_coords[i]
                    tx, ty = t_coords[j]
                    new_c.append(CCell((ex + tx) / 2, (ey + ty) / 2))
                    taken_t.add(j)
                    break
            else:
                remaining_e.append(ECell(*e_coords[i]))

        self.t_cells = [t for j, t in enumerate(self.t_cells) if j not in taken_t]
        self.new_c_cells = new_c
        self.e_cells = remaining_e

    def _c_cell_behavior(self):
        remaining_c = []
        for c in self.existing_c_cells:
            rnd = np.random.rand()
            if rnd < self.k_off:
                self.e_cells.append(ECell(c.x, c.y))
                self.t_cells.append(TCell(c.x, c.y))
            elif rnd < self.k_off + self.k_kill:
                self.e_cells.append(ECell(c.x, c.y))
            else:
                remaining_c.append(c)
        self.existing_c_cells = remaining_c

    def _cell_move(self):
        moved = []
        for e in self.e_cells:
            dx, dy = np.random.normal(0, self.m, size=2)
            x, y = self.well.apply_boundary(e.x + dx, e.y + dy)
            moved.append(ECell(x, y))
        self.e_cells = moved

    def _cell_grow(self):
        new_e = []
        for e in self.e_cells:
            if np.random.rand() < self.g_E:
                dx, dy = np.random.uniform(-self.r, self.r, 2)
                x, y = self.well.apply_boundary(e.x + dx, e.y + dy)
                new_e.append(ECell(x, y))
        self.e_cells.extend(new_e)

        new_t = []
        for t in self.t_cells:
            if np.random.rand() < self.g_T:
                dx, dy = np.random.uniform(-self.r, self.r, 2)
                x, y = self.well.apply_boundary(t.x + dx, t.y + dy)
                new_t.append(TCell(x, y))
        self.t_cells.extend(new_t)

    def _log(self):
        self.history["E"].append(len(self.e_cells))
        self.history["T"].append(len(self.t_cells))
        self.history["C"].append(len(self.existing_c_cells) + len(self.new_c_cells))
        self.existing_c_cells += self.new_c_cells
        self.new_c_cells = []

    def _step(self):
        self._cell_move()
        self._combine_behavior()
        self._c_cell_behavior()
        self._cell_grow()
        self._log()

    def run(self):
        unchanged = 0
        prev_T = self.history["T"][-1]
        for _ in range(self.N):
            self._step()
            curr_T = self.history["T"][-1]
            if prev_T * (1 - self.early_stop[1]) <= curr_T <= prev_T * (1 + self.early_stop[1]):
                unchanged += 1
            else:
                unchanged = 0
            prev_T = curr_T
            if curr_T == 0 and self.history["C"][-1] == 0:
                break
            if self.history["E"][-1] == 0 and self.history["C"][-1] == 0:
                break
            if unchanged >= self.early_stop[0]:
                break
        self.simulated = True

# --- Run ABM and Collect Full Data ---
N_steps = 200
E_0 = 100
T_0 = 100
n_replicates = 20

E_all, T_all, C_all = [], [], []
records = []

for seed in tqdm(range(n_replicates), desc="Simulating ABM replicates"):
    sim = WellSimulation(E_0=E_0, T_0=T_0, r=0.02, m=0.02, N=N_steps, L=1.0,
                         k_on=0.8, k_off=0.6, k_kill=0.2,
                         g_E=0.0, g_T=0.05,
                         early_stop=(10, 0.01), log_all=False, seed=seed)
    sim.run()
    E_all.append(sim.history["E"])
    T_all.append(sim.history["T"])
    C_all.append(sim.history["C"])
    for t in range(len(sim.history["T"])):
        records.append({"replicate": seed, "timestep": t,
                        "E": sim.history["E"][t],
                        "T": sim.history["T"][t],
                        "C": sim.history["C"][t]})

# --- Long Format ---
long_df = pd.DataFrame.from_records(records)
long_df.to_csv("ABM_E_T_C_long.csv", index=False)

# --- Wide Format: Individual ---
max_len = max(len(max(E_all, key=len)), len(max(T_all, key=len)), len(max(C_all, key=len)))

def pad_to_max(lst):
    return lst + [np.nan] * (max_len - len(lst))

E_df = pd.DataFrame([pad_to_max(e) for e in E_all]).T
T_df = pd.DataFrame([pad_to_max(t) for t in T_all]).T
C_df = pd.DataFrame([pad_to_max(c) for c in C_all]).T

E_df.columns = T_df.columns = C_df.columns = [f"rep_{i}" for i in range(n_replicates)]
E_df.insert(0, "timestep", np.arange(max_len))
T_df.insert(0, "timestep", np.arange(max_len))
C_df.insert(0, "timestep", np.arange(max_len))

E_df.to_csv("ABM_E_wide.csv", index=False)
T_df.to_csv("ABM_T_wide.csv", index=False)
C_df.to_csv("ABM_C_wide.csv", index=False)

# --- Aggregated Statistics ---
aggr_df = pd.DataFrame({
    "timestep": np.arange(max_len),
    "E_mean": np.nanmean(E_df.drop("timestep", axis=1), axis=1),
    "T_mean": np.nanmean(T_df.drop("timestep", axis=1), axis=1),
    "C_mean": np.nanmean(C_df.drop("timestep", axis=1), axis=1),
    "E_std": np.nanstd(E_df.drop("timestep", axis=1), axis=1),
    "T_std": np.nanstd(T_df.drop("timestep", axis=1), axis=1),
    "C_std": np.nanstd(C_df.drop("timestep", axis=1), axis=1),
})
aggr_df.to_csv("ABM_ETC_summary.csv", index=False)

print("✅ All CSV files saved.")

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
# Parameters
lambda_ = 0.05  # proliferation rate
mu = 0.02       # death rate
N = 10
# Step 1: Create the transition matrix A
A = np.zeros((N + 1, N + 1))
for n in range(N + 1):
    # Inflow from (n-1) due to proliferation
    if n > 0:
        A[n, n - 1] = lambda_ * (n - 1)
    # Inflow from (n+1) due to death
    if n < N:
        A[n, n + 1] = mu * (n + 1)
    # Outflow from state n
    A[n, n] = - (lambda_ + mu) * n
# Step 2: Define the system of ODEs
def master_eq(t, P):
    return A @ P  # Matrix-vector multiplication
# Step 3: Initial condition
P0 = np.zeros(N + 1)
P0[5] = 1.0
# Step 4: Solve the system
t_span = (0, 100)
t_eval = np.linspace(*t_span, 500)
sol = solve_ivp(master_eq, t_span, P0, t_eval=t_eval)
# Step 5: Plot distribution at selected time points
plt.figure(figsize=(10, 6))
for i in [0, 100, 200, 300, 499]:
    plt.plot(range(N + 1), sol.y[:, i], label=f't={t_eval[i]:.1f}')
plt.xlabel("Number of Tumor Cells (n)")
plt.ylabel("Probability P_n(t)")
plt.title("Tumor Cell Distribution Over Time")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()
# Step 6: Plot the mean ⟨n(t)⟩ over time
expected_n = np.dot(np.arange(N + 1), sol.y)
plt.figure(figsize=(8, 5))
plt.plot(t_eval, expected_n, label='⟨n(t)⟩', color='purple')
plt.xlabel("Time")
plt.ylabel("Expected Number of Tumor Cells")
plt.title("Mean Tumor Cell Count Over Time")
plt.grid(True)
plt.tight_layout()
plt.show()
n0 = 10  # initial number of tumor cells
expected_n = n0 * np.exp((lambda_ - mu) * t_eval)
plt.figure(figsize=(8, 5))
plt.plot(t_eval, expected_n, label=r'$\langle n(t) \rangle$', color='purple')
plt.xlabel("Time")
plt.ylabel("Expected Number of Tumor Cells")
plt.title("Mean Tumor Cell Count Over Time (Analytical)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# --- Colab Setup ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize
import re
from google.colab import files

# --- Upload your 9 CSV files ---
uploaded = files.upload()

# --- Parse E0, T0 from filenames like: E-1000_T-100_AGG.csv ---
def extract_initial_conditions(filename):
    match = re.search(r"E-(\d+)_T-(\d+)", filename)
    if match:
        E0 = int(match.group(1))
        T0 = int(match.group(2))
        return E0, T0
    else:
        raise ValueError(f"Filename {filename} does not match expected pattern.")

# --- 1-ODE Model Function (Analytical Solution) ---
def model_T(t, T0, E0, k_on, k_off, k_kill, g):
    rate = g - (k_on * k_kill / (k_off + k_kill)) * E0
    return T0 * np.exp(rate * t)

# --- Objective Function: Avg Normalized RMSE ---
def objective(params, datasets):
    k_on, k_off, k_kill, g = params
    total_error = 0
    for data in datasets:
        t = data['time']
        T_obs = data['T']
        T0 = T_obs[0]
        E0 = data['E0']
        T_pred = model_T(t, T0, E0, k_on, k_off, k_kill, g)
        rmse = np.sqrt(np.mean((T_obs - T_pred) ** 2))
        norm = np.mean(T_obs)
        total_error += rmse / norm
    return total_error / len(datasets)

# --- Load CSVs ---
datasets = []
for fname in uploaded:
    if fname.endswith(".csv"):
        df = pd.read_csv(fname)
        E0, T0 = extract_initial_conditions(fname)
        t = np.linspace(0, 24, len(df))  # 96 steps over 24 hrs
        datasets.append({
            'filename': fname,
            'E0': E0,
            'T0': df['T'].iloc[0],
            'T': df['T'].values,
            'time': t
        })

# --- Initial Parameter Guess and Bounds ---
x0 = [0.3, 0.3, 0.007, 0.007]  # [k_on, k_off, k_kill, g]
bounds = [(0.0001, 1), (0.0001, 1), (0.0001, 1), (-0.1, 0.1)]

# --- Fit the Model ---
result = minimize(objective, x0, args=(datasets,), bounds=bounds, method='L-BFGS-B')
k_on, k_off, k_kill, g = result.x

# --- Print Results ---
print(f"✅ Best-fit Parameters:")
print(f"   k_on   = {k_on:.4f}")
print(f"   k_off  = {k_off:.4f}")
print(f"   k_kill = {k_kill:.4f}")
print(f"   g      = {g:.4f}")
print(f"Avg Normalized RMSE = {result.fun:.4f}")

# --- Plot Observed vs Predicted T(t) ---
fig, axes = plt.subplots(3, 3, figsize=(12, 9))
axes = axes.flatten()

for i, data in enumerate(datasets):
    t = data['time']
    T_obs = data['T']
    T0 = data['T0']
    E0 = data['E0']
    T_pred = model_T(t, T0, E0, k_on, k_off, k_kill, g)

    ax = axes[i]
    ax.plot(t, T_obs, 'k--', label='Observed T')
    ax.plot(t, T_pred, 'r-', label='Model T')
    ax.set_title(f"E₀={E0}, T₀={int(T0)}")
    ax.set_xlabel("Time (hours)")
    ax.set_ylabel("Tumor Count (T)")
    ax.legend()

plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from google.colab import files

# Upload
uploaded = files.upload()


for fname in uploaded:
    df = pd.read_csv(fname)
    df.columns = df.columns.str.strip()

#  CAR Only
df_car = df[df['Effectors'] == 'CAR'].copy()
df_car = df_car.sort_values(by='Tars_per_well')
#T0_values = df_car['Mean Result'].values
T0_values = df_car['Tars_per_well'].values
E0_values = E:T * Tars_per_well

t_obs = 24

# Tumor Count Model at 24h
def model_T24(T0, E0, k_on, k_off, k_kill, g):
    rate = g - (k_on * k_kill / (k_off + k_kill)) * E0
    return T0 * np.exp(rate * t_obs)

#RMSE Objective
def objective(params):
    k_on, k_off, k_kill, g = params
    total_error = 0
    for T0, E0 in zip(T0_values, E0_values):
        T_pred = model_T24(T0, E0, k_on, k_off, k_kill, g)
        total_error += (T_pred - T0)**2
    return np.sqrt(total_error / len(T0_values))

# Fit Parameters
x0 = [0.001, 0.5, 0.001, 0.01]
bounds = [(0.0001, 1), (0.0001, 1), (0.0001, 1), (-0.1, 0.1)]
result = minimize(objective, x0, bounds=bounds, method='L-BFGS-B')
k_on, k_off, k_kill, g = result.x

# Add Model Prediction Column
df_car['T_pred'] = df_car.apply(
    lambda row: model_T24(row['Mean Result'], row['Tars_per_well'], k_on, k_off, k_kill, g),
    axis=1
)

#  Print Parameters
print("✅ Best-fit Parameters (Real Data at 24h):")
print(f"   k_on   = {k_on:.4f}")
print(f"   k_off  = {k_off:.4f}")
print(f"   k_kill = {k_kill:.4f}")
print(f"   g      = {g:.4f}")
print(f"RMSE     = {result.fun:.4f}")

#  Groups
colors = {5000: 'blue', 10000: 'green', 20000: 'orange'}
markers = {5000: 'o', 10000: 's', 20000: '^'}

plt.figure(figsize=(10, 6))
for group in df_car['Tars_per_well'].unique():
    sub = df_car[df_car['Tars_per_well'] == group]
    plt.plot(sub['E:T'], sub['Mean Result'], linestyle='--', marker=markers[group],
             color=colors[group], label=f"Observed (E₀={group})")
    plt.plot(sub['E:T'], sub['T_pred'], linestyle='-', color=colors[group], linewidth=2,
             label=f"Model (E₀={group})")

plt.xlabel("E:T Ratio")
plt.ylabel("Tumor Count at 24h")
plt.title("Observed vs. Predicted Tumor Count (CAR Only, Real Data)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()